### ISSUE TITLE
OpenServiceBroker spec has mandatory `organization_guid` and `space_guid`

### ISSUE THREAD

**Issue by dvaldivia** [IBM/sample-resource-service-brokers#2]
According to the specification at https://github.com/openservicebrokerapi/servicebroker

For a  service provisioning request the fields `organization_guid` and `space_guid` are required, but in the documentation it's not specified that they should be omitted, perhaps this should be clarified.

**Comment by rboykin** [comment]
The spec also shows `organization_guid` and `space_guid` as deprecated in favor of the generic `context`. https://github.com/openservicebrokerapi/servicebroker/blob/v2.16/spec.md#body-3.

Since the IBM Cloud service broker is not implementing the CF-specific protocol, but the IBM resource controller protocol, the `organization_guid` and `space_guid` are not applicable. You will notice that the sample code pulls different fields from the `context` for use in the IBM Cloud.
